/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  desc?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Milestone = {
  _id: string;
  _type: 'milestone';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  year?: string;
  desc?: string;
};

export type Contact = {
  _id: string;
  _type: 'contact';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  scope?:
    | 'ui_ux'
    | 'ux_strategy'
    | 'design_strategy'
    | 'web_design'
    | 'frontend_development'
    | 'website_redesign'
    | 'product_strategy'
    | 'content_and_information_architecture'
    | 'motion_and_interaction_design'
    | 'studio_partnership';
  message?: string;
};

export type Newsletter = {
  _id: string;
  _type: 'newsletter';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
};

export type Review = {
  _id: string;
  _type: 'review';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  title?: string;
  role?: string;
  mainImage?: BlockImage;
  desc?: string;
};

export type BlockImage = {
  _type: 'blockImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  subTitle?: string;
  price?: number;
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type Award = {
  _id: string;
  _type: 'award';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  awardedTitle?: string;
  slug?: Slug;
  awardedCategory?: string;
  awardedDate?: string;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  slug?: Slug;
  role?: string;
  mainImage?: BlockImage;
  bio?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  finishedAt?: string;
  scope?: string;
  timeline?: string;
  mainImage?: BlockImage;
  logoImage?: BlockImage;
  desc?: BlockContent;
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: string;
  mainImage?: BlockImage;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | UtilityPage
  | BlockContent
  | Slug
  | Milestone
  | Contact
  | Newsletter
  | Faq
  | Review
  | BlockImage
  | Service
  | Award
  | TeamMember
  | Project
  | Blog
  | Category
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: ALL_BLOGS_QUERY
// Query: {"blogs": *[_type == 'blog'          && defined(slug.current)]          | order(publishedAt desc)          [$startIndex...$endIndex]{            title,            slug,            publishedAt,            author->{              name,              slug,              mainImage{                alt,                asset->{url}              }            },            mainImage{              alt,              asset->{url}            },            category->{              name,            },          },        "total": count(*[_type == 'blog'                && defined(slug.current)]),}
export type ALL_BLOGS_QUERYResult = {
  blogs: Array<{
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    author: {
      name: string | null;
      slug: Slug | null;
      mainImage: {
        alt: string | null;
        asset: {
          url: string | null;
        } | null;
      } | null;
    } | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    category: {
      name: string | null;
    } | null;
  }>;
  total: number;
};
// Variable: BLOG_QUERY
// Query: *[_type == 'blog' && slug.current == $slug][0]{  title,  slug,  publishedAt,  author->{    name,    slug,    mainImage{        alt,        asset->{url}    }  },  mainImage{    alt,    asset->{url}  },  desc,  category->{    name  },  "relatedPosts": *[_type == 'blog'                         && category._ref == ^.category._ref                        && _id != ^._id]{                          title,                          slug,                          publishedAt,                          author->{                            name,                            slug,                            mainImage{                              alt,                              asset->{url}                            }                          },                          mainImage{                            alt,                            asset->{url}                          },                          category->{                            name,                          },                        } }
export type BLOG_QUERYResult = {
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    slug: Slug | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  desc: BlockContent | null;
  category: {
    name: string | null;
  } | null;
  relatedPosts: Array<{
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    author: {
      name: string | null;
      slug: Slug | null;
      mainImage: {
        alt: string | null;
        asset: {
          url: string | null;
        } | null;
      } | null;
    } | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    category: {
      name: string | null;
    } | null;
  }>;
} | null;
// Variable: AUTHOR_QUERY
// Query: *[_type == 'author' && slug.current == $slug][0]{  name,  mainImage{    alt,    asset->{url}  },  bio,  slug }
export type AUTHOR_QUERYResult = {
  name: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  bio: string | null;
  slug: Slug | null;
} | null;
// Variable: ALL_PROJECTS_QUERY
// Query: {  "projects": *[_type == 'project' && defined(slug.current)] | order(finishedAt desc) [$startIndex...$endIndex] {  name,  slug,  finishedAt,  scope,  timeline,  mainImage{    alt,    asset->{url}  },  logoImage{    alt,    asset->{url}  } }, "total": count(*[_type == 'project' && defined(slug.current) ])}
export type ALL_PROJECTS_QUERYResult = {
  projects: Array<{
    name: string | null;
    slug: Slug | null;
    finishedAt: string | null;
    scope: string | null;
    timeline: string | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    logoImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
  }>;
  total: number;
};
// Variable: PROJECT_QUERY
// Query: *[_type == 'project' && slug.current ==  $slug][0]{  name,  slug,  finishedAt,  scope,  timeline,  desc,  mainImage{    alt,    asset->{url}  },  logoImage{    alt,    asset->{url}  },  "otherProjects": *[_type == 'project'                      && _id != ^.id]{                          name,                          slug,                          finishedAt,                          scope,                          timeline,                          desc,                          mainImage{                            alt,                            asset->{url}                          },                          logoImage{                            alt,                            asset->{url}                          },                      } }
export type PROJECT_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  finishedAt: string | null;
  scope: string | null;
  timeline: string | null;
  desc: BlockContent | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  logoImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  otherProjects: Array<{
    name: string | null;
    slug: Slug | null;
    finishedAt: string | null;
    scope: string | null;
    timeline: string | null;
    desc: BlockContent | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    logoImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
  }>;
} | null;
// Variable: ALL_TEAM_MEMBERS_QUERY
// Query: *[_type == 'teamMember' && defined(slug.current)]{  fullName,  role,  slug,  mainImage{    alt,    asset->{url}  },  bio }
export type ALL_TEAM_MEMBERS_QUERYResult = Array<{
  fullName: string | null;
  role: string | null;
  slug: Slug | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  bio: string | null;
}>;
// Variable: TEAM_MEMBER_QUERY
// Query: *[_type == 'teamMember' && slug.current == $slug][0]{  fullName,  role,  slug,  mainImage{    alt,    asset->{url}  },  bio }
export type TEAM_MEMBER_QUERYResult = {
  fullName: string | null;
  role: string | null;
  slug: Slug | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  bio: string | null;
} | null;
// Variable: ALL_AWARDS_QUERY
// Query: *[_type == 'award' && defined(slug.current)]{  awardedTitle,  awardedDate,  slug,  awardedCategory }
export type ALL_AWARDS_QUERYResult = Array<{
  awardedTitle: string | null;
  awardedDate: string | null;
  slug: Slug | null;
  awardedCategory: string | null;
}>;
// Variable: ALL_SERVICES_QUERY
// Query: {  "services": *[_type == 'service' && defined(slug.current)]  | order(_updatedAt desc)  [$startIndex...$endIndex]{  name,  slug,  mainImage{    alt,    asset->{url}  },  subTitle,  price },  "total": count(*[_type == 'service'                  && defined(slug.current)])}
export type ALL_SERVICES_QUERYResult = {
  services: Array<{
    name: string | null;
    slug: Slug | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    subTitle: string | null;
    price: number | null;
  }>;
  total: number;
};
// Variable: SERVICE_QUERY
// Query: *[_type == 'service' && slug.current == $slug][0]{  name,  slug,  desc,  mainImage{    alt,    asset->{url}  },  subTitle,  price,  "otherServices": *[_type == 'service'                    && _id != ^._id]{                      name,                      slug,                      desc,                      mainImage{                        alt,                        asset->{url}                      },                      subTitle,                      price,                    } }
export type SERVICE_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  desc: BlockContent | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  subTitle: string | null;
  price: number | null;
  otherServices: Array<{
    name: string | null;
    slug: Slug | null;
    desc: BlockContent | null;
    mainImage: {
      alt: string | null;
      asset: {
        url: string | null;
      } | null;
    } | null;
    subTitle: string | null;
    price: number | null;
  }>;
} | null;
// Variable: ALL_REVIEWS_QUERY
// Query: *[_type == 'review']{  fullName,  role,  mainImage{    alt,    asset->{url}  },  desc,  title }
export type ALL_REVIEWS_QUERYResult = Array<{
  fullName: string | null;
  role: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  desc: string | null;
  title: string | null;
}>;
// Variable: ALL_FAQS_QUERY
// Query: *[_type == 'faq']{  question,  answer}
export type ALL_FAQS_QUERYResult = Array<{
  question: string | null;
  answer: string | null;
}>;
// Variable: ALL_MILESTONES_QUERY
// Query: *[_type == 'milestone' && defined(slug.current)]{  title,  slug,  year,  desc }
export type ALL_MILESTONES_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  year: string | null;
  desc: string | null;
}>;
// Variable: UTILITY_PAGE_QUERY
// Query: *[_type == 'utilityPage' && slug.current == $slug][0]{  name,  slug,  desc }
export type UTILITY_PAGE_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  desc: BlockContent | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '{"blogs": *[_type == \'blog\'\n          && defined(slug.current)]\n          | order(publishedAt desc)\n          [$startIndex...$endIndex]{\n            title,\n            slug,\n            publishedAt,\n            author->{\n              name,\n              slug,\n              mainImage{\n                alt,\n                asset->{url}\n              }\n            },\n            mainImage{\n              alt,\n              asset->{url}\n            },\n            category->{\n              name,\n            },\n          },\n        "total": count(*[_type == \'blog\'\n                && defined(slug.current)]),\n}': ALL_BLOGS_QUERYResult;
    "*[_type == 'blog'\n && slug.current == $slug][0]{\n  title,\n  slug,\n  publishedAt,\n  author->{\n    name,\n    slug,\n    mainImage{\n        alt,\n        asset->{url}\n    }\n  },\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  desc,\n  category->{\n    name\n  },\n  \"relatedPosts\": *[_type == 'blog' \n                        && category._ref == ^.category._ref\n                        && _id != ^._id]{\n                          title,\n                          slug,\n                          publishedAt,\n                          author->{\n                            name,\n                            slug,\n                            mainImage{\n                              alt,\n                              asset->{url}\n                            }\n                          },\n                          mainImage{\n                            alt,\n                            asset->{url}\n                          },\n                          category->{\n                            name,\n                          },\n                        }\n }": BLOG_QUERYResult;
    "*[_type == 'author'\n && slug.current == $slug][0]{\n  name,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  bio,\n  slug\n }": AUTHOR_QUERYResult;
    '{\n  "projects": *[_type == \'project\'\n && defined(slug.current)]\n | order(finishedAt desc)\n [$startIndex...$endIndex]\n {\n  name,\n  slug,\n  finishedAt,\n  scope,\n  timeline,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  logoImage{\n    alt,\n    asset->{url}\n  }\n },\n "total": count(*[_type == \'project\' && defined(slug.current) ])\n}': ALL_PROJECTS_QUERYResult;
    "*[_type == 'project'\n && slug.current ==  $slug][0]{\n  name,\n  slug,\n  finishedAt,\n  scope,\n  timeline,\n  desc,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  logoImage{\n    alt,\n    asset->{url}\n  },\n  \"otherProjects\": *[_type == 'project'\n                      && _id != ^.id]{\n                          name,\n                          slug,\n                          finishedAt,\n                          scope,\n                          timeline,\n                          desc,\n                          mainImage{\n                            alt,\n                            asset->{url}\n                          },\n                          logoImage{\n                            alt,\n                            asset->{url}\n                          },\n                      }\n }": PROJECT_QUERYResult;
    "*[_type == 'teamMember'\n && defined(slug.current)]{\n  fullName,\n  role,\n  slug,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  bio\n }": ALL_TEAM_MEMBERS_QUERYResult;
    "*[_type == 'teamMember'\n && slug.current == $slug][0]{\n  fullName,\n  role,\n  slug,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  bio\n }": TEAM_MEMBER_QUERYResult;
    "*[_type == 'award'\n && defined(slug.current)]{\n  awardedTitle,\n  awardedDate,\n  slug,\n  awardedCategory\n }": ALL_AWARDS_QUERYResult;
    '{\n  "services": *[_type == \'service\'\n && defined(slug.current)]\n  | order(_updatedAt desc)\n  [$startIndex...$endIndex]{\n  name,\n  slug,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  subTitle,\n  price\n },\n  "total": count(*[_type == \'service\'\n                  && defined(slug.current)])\n}': ALL_SERVICES_QUERYResult;
    "*[_type == 'service'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  desc,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  subTitle,\n  price,\n  \"otherServices\": *[_type == 'service'\n                    && _id != ^._id]{\n                      name,\n                      slug,\n                      desc,\n                      mainImage{\n                        alt,\n                        asset->{url}\n                      },\n                      subTitle,\n                      price,\n                    }\n }": SERVICE_QUERYResult;
    "*[_type == 'review']{\n  fullName,\n  role,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  desc,\n  title\n }": ALL_REVIEWS_QUERYResult;
    "*[_type == 'faq']{\n  question,\n  answer\n}": ALL_FAQS_QUERYResult;
    "*[_type == 'milestone'\n && defined(slug.current)]{\n  title,\n  slug,\n  year,\n  desc\n }": ALL_MILESTONES_QUERYResult;
    "*[_type == 'utilityPage'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  desc\n }": UTILITY_PAGE_QUERYResult;
  }
}
